"""Change appearance id to autoincrement integer

Revision ID: c5fd14ab9b63
Revises: f28165e43aca
Create Date: 2025-06-23 10:57:21.666665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5fd14ab9b63'
down_revision = 'f28165e43aca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appearances', schema=None) as batch_op:
        batch_op.alter_column(
               'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               postgresql_using='id::integer'
               )
        
        
   # Set the default sequence for autoincrement
    op.execute("CREATE SEQUENCE IF NOT EXISTS appearances_id_seq OWNED BY appearances.id;")
    op.execute("ALTER TABLE appearances ALTER COLUMN id SET DEFAULT nextval('appearances_id_seq');")
    op.execute("SELECT setval('appearances_id_seq', COALESCE((SELECT MAX(id) FROM appearances), 1), false);")  
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appearances', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
